server:
  port: 8080
  context-path: /demo


spring:
  redis:
    host: 127.0.0.1
    password:
    port: 10061
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1